# SPDX-FileCopyrightText: 2024 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

on: [push, pull_request]

name: Build binaries
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Get sources
        uses: actions/checkout@v2
      - name: Install Alire
        uses: alire-project/setup-alire@v3
        with:
          toolchain: gnat_arm_elf gnat_native gprbuild^22
      - name: Build and test
        run: |
          alr build
          alr -C tests run
          alr -C demos/gtkada build
          alr index --add git+https://github.com/reznikmm/stm32-alire-index --name stm32
          alr -C demos/stm32f4 build
