on: [push, pull_request]

name: Build binaries
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Get sources
        uses: actions/checkout@v2
      - name: Install Alire
        uses: alire-project/setup-alire@v3
      - name: Build and test
        run: |
          alr build
          alr -C tests run
          alr -C demos/gtkada build
